#!/usr/bin/env node

/**
 * Environment Variables Injector for Static Frontend
 * Reads .env file and creates a JavaScript file with environment variables
 */

const fs = require('fs');
const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '..', '..', '.env') });

// Get all environment variables that start with EF_CMS_
const envVars = {};
Object.keys(process.env).forEach(key => {
    if (key.startsWith('EF_CMS_')) {
        envVars[key] = process.env[key];
    }
});

// Create the JavaScript content
const jsContent = `/**
 * Environment Variables for EF CMS Frontend
 * This file is automatically generated from .env file
 * DO NOT EDIT MANUALLY
 */

window.EF_ENV_VARS = ${JSON.stringify(envVars, null, 2)};

console.log('🔧 Environment variables loaded:', Object.keys(window.EF_ENV_VARS).length, 'variables');
`;

// Write the file
const outputPath = path.join(__dirname, '..', 'js', 'api', 'env-vars.js');
fs.writeFileSync(outputPath, jsContent);

console.log('✅ Environment variables injected into:', outputPath);
console.log('📋 Variables found:', Object.keys(envVars).join(', '));
